language: ruby
rvm:
- 2.0.0
branches:
  only:
  - develop
  except:
  - master
before_install:
- gem update
before_script:
- git config --global user.name "responsivetequila"
- git config --global user.email "leonel.perea@cimat.mx"
- git clone --quiet --branch=master https://${GH_TOKEN}@github.com/responsivetequila/responsivetequila.github.io.git _site
after_success:
- bundle exec rake deploy
env:
  global:
  - secure: BMZ4nvASGi2F3TZ9GDvNWnBa87QvJbWMYGJKZEE69zuApAGzM0FGQGXlYWAXZdt13mSDC92bF+CzaSrkguMvtERRC5QV/+tRqhEr5E/JGz01iHDYfL+fUEBJ0UaiE9XyQJLN79XNNC+U2RHev/SlxMgOeIAlkONzUVbv5UMlu5g=