name: Responsive Tequila
description: "Blog de Responsive Tequila"
url: "http://responsivetequila.github.io"
paginate: 10
markdown: redcarpet
comments: true
pygments: true
permalink: pretty

exclude: [Gemfile, Gemfile.lock, Rakefile.rb, vendor, test]
include: [.travis.yml, .htaccess]