author: 'iLeonelperea, AntonioCabrera'
baseurl: /
comments: true
description: "Blog de Responsive Tequila"
markdown: redcarpet
name: Responsive Tequila
paginate: 10
paginate_path: /blog/page:num/
permalink: /blog/:year/:month/:day/:title
highlighter: pygments
relative_permalinks: false
url: "http://responsivetequila.mx"
safe: true
timezone: America/Mexico City
excerpt_separator: "<!-- more -->"

exclude: [Gemfile, Gemfile.lock, Rakefile.rb, vendor, test]
include: [_pages, .travis.yml, .htaccess]